In [7]:
import pandas as pd
import pickle
path = "/content/sample_data/knn_model.pickle"
with open(path,'rb') as f:
    knn_new = pickle.load(f)

In [8]:

path_2 = "/content/sample_data/scaler.pickle"
with open(path_2,'rb') as f:
     scaler_new = pickle.load(f)

In [11]:
path_3 = "/content/drive/MyDrive/Excel-and-CSV-files/new_customers.csv"
df = pd.read_csv(path_3)
df.head()

Gender  Age  Salary  Product ID  Price
0    Male   24   38652           3   4446
1  Female   47   64727           1   5188
2    Male   46   54648           1   6193
3    Male   31   20018           3   4779
4    Male   58   77731           2   6855

In [12]:
len(df)

10

In [13]:
gender_encoded_new = pd.get_dummies(df['Gender'],drop_first=True)

In [14]:
gender_encoded_new

Male
0   True
1  False
2   True
3   True
4   True
5   True
6  False
7   True
8  False
9   True

In [15]:
df = pd.concat([df,gender_encoded_new],axis = 1)

In [16]:
df

Gender  Age  Salary  Product ID  Price   Male
0    Male   24   38652           3   4446   True
1  Female   47   64727           1   5188  False
2    Male   46   54648           1   6193   True
3    Male   31   20018           3   4779   True
4    Male   58   77731           2   6855   True
5    Male   28   55478           1   6153   True
6  Female   48   54211           2   7588  False
7    Male   31   60076           3   5238   True
8  Female   42   29290           1   5418  False
9    Male   50   21445           1   5598   True

In [17]:
x = df[['Male','Age','Salary','Price']].to_numpy()
x

array([[True, 24, 38652, 4446],
       [False, 47, 64727, 5188],
       [True, 46, 54648, 6193],
       [True, 31, 20018, 4779],
       [True, 58, 77731, 6855],
       [True, 28, 55478, 6153],
       [False, 48, 54211, 7588],
       [True, 31, 60076, 5238],
       [False, 42, 29290, 5418],
       [True, 50, 21445, 5598]], dtype=object)

In [20]:
x_new_scaler = scaler_new.fit_transform(x)
x_new_scaler

array([[ 0.65465367, -1.54774434, -0.48875298, -1.42543997],
       [-1.52752523,  0.60971747,  0.93112246, -0.61159228],
       [ 0.65465367,  0.51591478,  0.38228547,  0.49072164],
       [ 0.65465367, -0.89112553, -1.50343981, -1.06019565],
       [ 0.65465367,  1.64154703,  1.63923599,  1.21682294],
       [ 0.65465367, -1.17253359,  0.42748189,  0.44684845],
       [-1.52752523,  0.70352015,  0.35848928,  2.02079916],
       [ 0.65465367, -0.89112553,  0.67785916, -0.55675079],
       [-1.52752523,  0.14070403, -0.99854681, -0.35932143],
       [ 0.65465367,  0.89112553, -1.42573465, -0.16189207]])

In [22]:
y_new_pred = knn_new.predict(x_new_scaler)

In [23]:
y_new_pred

array([0, 1, 0, 0, 0, 0, 0, 1, 0, 0])

In [25]:
df['will_purchase'] = y_new_pred

In [26]:
df

Gender  Age  Salary  Product ID  Price   Male  will_purchase
0    Male   24   38652           3   4446   True              0
1  Female   47   64727           1   5188  False              1
2    Male   46   54648           1   6193   True              0
3    Male   31   20018           3   4779   True              0
4    Male   58   77731           2   6855   True              0
5    Male   28   55478           1   6153   True              0
6  Female   48   54211           2   7588  False              0
7    Male   31   60076           3   5238   True              1
8  Female   42   29290           1   5418  False              0
9    Male   50   21445           1   5598   True              0

In [27]:
df.to_csv("project_1_testing.csv",index = False)